### PR TITLE
✨ Add new SyncEngine, support async and sync code - with fixed session

### PR DESCRIPTION
**Pull request by tiangolo**
✨ Add new SyncEngine, support async and sync code - with fixed session

This is the same as https://github.com/art049/odmantic/pull/225, but it includes the fixes to share the same session in https://github.com/art049/odmantic/pull/227

This would supersede https://github.com/art049/odmantic/pull/225 if the session fix in https://github.com/art049/odmantic/pull/227 is accepted.

I'm doing it here as an additional PR because there are a couple of changes and fixes needed in the new `SyncEngine` to handle that same issue with the session.

### CODE REVIEW

**Comment by tiangolo** [comment]
I added a couple of small tests to check the errors when `motor` is **not** installed, this should fix the line missing coverage. :sunglasses:

**Review by art049 — APPROVED** [review]

**Comment by art049** [comment]
Awesome @tiangolo !
I just reviewed everything and it looks perfect to me.

There is just a tiny rebase required and it will be good for a merge!
I can handle the documentation part if you want, it shouldn't be that long.

Can't wait to see what you plan to do with bulk_writes and switch_collection!

**Comment by art049** [comment]
Actually I though about it again and it might be quite painful for existing users to have to change the dependency in order to upgrade to the new release.
I think it would be smoother to let the motor dependency as required.
I'm not totally sure but wdyt @tiangolo ?

**Comment by art049** [comment]
Merged in #242 ! 
Many thanks @tiangolo ! 🔥

**Comment by tiangolo** [comment]
Awesome, thanks a lot! 🚀 

About having Motor as optional or not, I think that's totally up to you. I get it that as ODMantic was always Motor-specific it could feel weird suddenly having that as optional.

If it was a new project, I guess it would be a no-brainer but I get that it can make sense to keep it required for backwards compatibility.

Maybe it can be done in a future release after having some warning in the docs for a while or something like that. Anyway, I don't feel strongly about it in one way or the other. 😅

**Pull request closed without merging**
