### PR TITLE
Transaction depends on server type

### LINKED ISSUE #86: 🔴 Transactions are not used now!
# Bug

In the `_save()` method transaction's `session` is not passed to `update_one()` request. 
https://github.com/art049/odmantic/blob/541d4119fe5e558491ec21b223eb9242ccde4b91/odmantic/engine.py#L315-L320

**It means that transaction is NOT USED NOW!**

## How to fix?
It's not enough to just pass the `session` to request.
In MongoDB transactions are not available for Standalone. 
This simple way Standalone users will get exceptions for every `save()` call :cry: 

So we need to define the users of Standalone version and not start a transaction for them.
Example:
```python
if self.client._server_property('server_type') == SERVER_TYPE.Standalone:
    await self._save(instance, None, **kwargs)
else:
    async with await self.client.start_session() as s:
        async with s.start_transaction():
            await self._save(instance, s, **kwargs)
```

P.S.: I don't know how to properly check `ServerType` without protected `_server_property` method :(

### LINKED ISSUE #87: `modified` mark is not cleared for embedded models on save
# Bug
`modified` mark is not cleared for embedded models on save

### Current Behavior
On `save()` method `__fields_modified__` set is cleared only for the top-level instance.
https://github.com/art049/odmantic/blob/541d4119fe5e558491ec21b223eb9242ccde4b91/odmantic/engine.py#L351

### Expected behavior
On `save()` method `__fields_modified__` set  should be cleared for the entire tree of embedded instances.

### PR DESCRIPTION
**Pull request by Olegt0rr**
Fixes #86 
Fixes #87 (added it here as it interfered with the implementation)

### CODE REVIEW

**Comment by Olegt0rr** [comment]
@art049 , need help!
To cover tests we need different types of mongo servers. I don't know how to implement it.

**Comment by art049** [comment]
I will add a new element in the CI array so we can test as well on replicasets and sharded clusters :smile: 

It would probably be helpful to be able to try it locally as well, an easy way would be to add a new task command to launch a dockerized mongo with other settings instead of the standalone one (keeping both of them):
https://github.com/art049/odmantic/blob/5756ddbb598241c9bbbacff3e0d941fbc8b26789/Taskfile.yml#L18-L23

I think we could just create a one member replicaset (basically simply adding `--replSet repl-set` to the run options)

For testing with mongos locally, it might be more difficult but i will have a look into it.

**Comment by art049** [comment]
@Olegt0rr I finally merged #91 ! Sorry for the delay but at least now it should be possible for you to configure the new tests :).
Tell me if you need some help to figure out the testing !

**Comment by Olegt0rr** [comment]
> @Olegt0rr I finally merged #91 ! Sorry for the delay but at least now it should be possible for you to configure the new tests :).
> Tell me if you need some help to figure out the testing !

I'm not sure I can figure it out.
Busy now + bad in testing
Can you help to cover it?

**Comment by art049** [comment]
Yes, sure no problem. Thanks for letting me know 😉

**Comment by art049** [comment]
Transfered to #117. Thanks @Olegt0rr for the inital work.

**Pull request closed without merging**
