### PR TITLE
Integrate pydantic v2

### PR DESCRIPTION
**Pull request by art049**

### CODE REVIEW

**Comment by 50Bytes-dev** [comment]
```python
class Item(Model):
    images: Optional[List[str]] = None
```
This code raise error "Subscripted generics cannot be used with class and instance checks"

**Comment by Galtozzy** [comment]
Are there any updates to this PR? Would be awesome to have this stuff in a main branch since FastAPI is on a V2 of pydantic for almost 3 months now.

**Comment by StandinKP** [comment]
No updates to this yet? Not able to use this with latest FastAPI and Pydantic versions till this get merged. Any update would be appreciated. Thanks

**Comment by art049** [comment]
> No updates to this yet? Not able to use this with latest FastAPI and Pydantic versions till this get merged. Any update would be appreciated. Thanks

Yes sorry it took much time than expected. I'm back at it rn :)

**Comment by art049** [comment]
Finally it's ready :smile: 
Release coming soon :hammer_and_wrench:

**Comment by blink1073** [comment]
:tada: nice work @art049!

**Comment by StandinKP** [comment]
Very excited. Thanks @art049

**Pull request merged**
